name: Deploy Docs

on:
  push:
    branches:
      - "*"
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.11"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: 'Setup Python ${{ env.PYTHON_VERSION }}'
        uses: actions/setup-python@v6
        id: setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Make docs
        run: |
          cd docs && yarn && yarn build && ls build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs/build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
